### ISSUE TITLE
folder app didalam lib?

### ISSUE THREAD

**Issue by anandiamy** [FlutterWithGia/Flutter_Template#1]
#question

Kenapa di dalam `lib `ada folder `app`? kenapa tidak langsung saja?

**Comment by firgia** [comment]
@anandiamy repo ini belum mengimplementasikan flavor, ketika flavor sudah di implementasikan nanti akan ada beberapa main lagi, jadi folder app itu di buat hanya untuk terlihat lebih rapih saja

Untuk struktur yg lebih baik dari ini, bisa coba yg https://github.com/firgia/soca yang sudah menerapkan Flavor, unit & widget test dan ada cloud function juga. Tapi itu menggunakan bloc architecture
